#!/usr/bin/env python3
"""Sync the local DiscoveryX repo to the VM over SFTP.

Uploads only changed files. With ``--prune`` it also removes files on the VM
that no longer exist locally, so the two trees stay identical. Runtime state
(datasets, models, vector store, audit log, projects/approvals, logs, builds,
``.env``) is never pruned.

    python scripts/vm_sync.py                 # upload changed files
    python scripts/vm_sync.py --prune-dry-run # list what --prune would delete
    python scripts/vm_sync.py --prune         # upload + delete stale files
"""
from __future__ import annotations

import os
import posixpath
import stat as stat_mod
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REMOTE_ROOT = os.environ.get("DX_REMOTE_ROOT", "discoveryx")

IGNORE_DIRS = {
    ".git", "node_modules", ".venv", "venv", "__pycache__", ".pytest_cache",
    ".ruff_cache", ".mypy_cache", ".next", "dist", "build", ".turbo",
    ".idea", ".vscode",
}
# Only ignored at the repository root (large local data), not when nested.
ROOT_IGNORE_DIRS = {"models", "reports", "artifacts"}
# Ignored by relative path (any depth).
IGNORE_PATHS = {"data/raw", "data/chroma", "data/audit", "data/catalog.json", "data/manifest.json", "frontend/dist"}
IGNORE_SUFFIX = {".pyc", ".pyo", ".duckdb", ".sqlite", ".sqlite3", ".log"}
IGNORE_NAMES = {".env"}

# Paths that exist only on the host and must never be pruned by --prune.
PROTECTED_PATHS = {
    ".env", ".env.local", ".env.production",
    "data/raw", "data/chroma", "data/audit", "data/datasets", "data/models",
    "data/projects.json", "data/approvals.json", "data/manifest.json", "data/catalog.json",
    "frontend/dist", "frontend/node_modules", "backend/.venv", "logs",
}
PROTECTED_DIRS = {
    ".git", "node_modules", ".venv", "venv", "logs",
    # tool caches: regenerated by any lint/test run, never worth reporting
    "__pycache__", ".pytest_cache", ".ruff_cache", ".mypy_cache",
}


def _protected(rel: str) -> bool:
    parts = rel.split("/")
    if any(p in PROTECTED_DIRS for p in parts):
        return True
    return any(rel == p or rel.startswith(p + "/") for p in PROTECTED_PATHS)


def _client():
    import paramiko

    host = os.environ["DX_VM_HOST"]
    user = os.environ.get("DX_VM_USER", "ubuntu")
    key = os.environ.get("DX_VM_KEY", os.path.expanduser("~/.ssh/discoveryx_vm"))
    c = paramiko.SSHClient()
    c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    c.connect(hostname=host, username=user, key_filename=key, timeout=25)
    return c


def _iter_files(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = Path(dirpath).relative_to(root)
        rel_posix = rel_dir.as_posix()
        at_root = rel_dir == Path(".")
        keep = []
        for d in dirnames:
            if d in IGNORE_DIRS:
                continue
            if at_root and d in ROOT_IGNORE_DIRS:
                continue
            child = d if rel_posix == "." else f"{rel_posix}/{d}"
            if child in IGNORE_PATHS:
                continue
            keep.append(d)
        dirnames[:] = keep
        for fn in filenames:
            if fn in IGNORE_NAMES:
                continue
            rel_file = fn if rel_posix == "." else f"{rel_posix}/{fn}"
            if rel_file in IGNORE_PATHS:
                continue
            p = Path(dirpath) / fn
            if p.suffix in IGNORE_SUFFIX:
                continue
            yield p


def _mkdirs(sftp, path: str, _cache: set[str] | None = None) -> None:
    if not path:
        return
    cache = _cache if _cache is not None else set()
    if path in cache:
        return
    absolute = path.startswith("/")
    parts = [p for p in path.split("/") if p]
    cur = "/" if absolute else ""
    for part in parts:
        if cur and not cur.endswith("/"):
            cur = f"{cur}/{part}"
        elif cur == "/":
            cur = f"/{part}"
        else:
            cur = part
        if cur in cache:
            continue
        try:
            sftp.stat(cur)
        except OSError:
            try:
                sftp.mkdir(cur)
            except OSError:
                pass
        cache.add(cur)
    cache.add(path)


def _remote_files(sftp, root: str) -> list[str]:
    """Relative paths of every file under ``root`` (skipping protected dirs)."""
    out: list[str] = []
    stack = [""]
    while stack:
        rel_dir = stack.pop()
        full = posixpath.join(root, rel_dir) if rel_dir else root
        try:
            entries = sftp.listdir_attr(full)
        except OSError:
            continue
        for e in entries:
            rel = f"{rel_dir}/{e.filename}" if rel_dir else e.filename
            if stat_mod.S_ISDIR(e.st_mode or 0):
                if e.filename in PROTECTED_DIRS or _protected(rel):
                    continue
                stack.append(rel)
            else:
                out.append(rel)
    return out


def _prune(sftp, dest_root: str, local_rel: set[str], *, dry_run: bool) -> int:
    removed = 0
    for rel in sorted(_remote_files(sftp, dest_root)):
        if rel in local_rel or _protected(rel):
            continue
        if not dry_run:
            try:
                sftp.remove(posixpath.join(dest_root, rel))
            except OSError as exc:
                print(f"  could not remove {rel}: {exc}", file=sys.stderr)
                continue
        print("  %s %s" % ("would remove" if dry_run else "removed", rel))
        removed += 1

    if not dry_run:
        # drop directories that are now empty (deepest first)
        dirs: list[str] = []
        stack = [""]
        while stack:
            rel_dir = stack.pop()
            full = posixpath.join(dest_root, rel_dir) if rel_dir else dest_root
            try:
                entries = sftp.listdir_attr(full)
            except OSError:
                continue
            for e in entries:
                rel = f"{rel_dir}/{e.filename}" if rel_dir else e.filename
                if stat_mod.S_ISDIR(e.st_mode or 0) and e.filename not in PROTECTED_DIRS and not _protected(rel):
                    dirs.append(rel)
                    stack.append(rel)
        for rel in sorted(dirs, key=lambda d: d.count("/"), reverse=True):
            full = posixpath.join(dest_root, rel)
            try:
                if not sftp.listdir(full):
                    sftp.rmdir(full)
            except OSError:
                pass
    return removed


def main() -> int:
    args = set(sys.argv[1:])
    prune = "--prune" in args
    dry_run = "--prune-dry-run" in args
    if args - {"--prune", "--prune-dry-run"}:
        print(__doc__, file=sys.stderr)
        return 2

    c = _client()
    try:
        sftp = c.open_sftp()
        home = sftp.normalize(".")
        dest_root = posixpath.join(home, REMOTE_ROOT)
        _mkdirs(sftp, dest_root)
        cache: set[str] = {dest_root}

        uploaded = 0
        skipped = 0
        local_rel: set[str] = set()
        for local in _iter_files(REPO):
            rel = local.relative_to(REPO).as_posix()
            local_rel.add(rel)
            remote = posixpath.join(dest_root, rel)
            _mkdirs(sftp, posixpath.dirname(remote), cache)
            st_local = local.stat()
            try:
                st = sftp.stat(remote)
                # skip unchanged files (same size and remote is not older)
                if st.st_size == st_local.st_size and int(st.st_mtime) >= int(st_local.st_mtime):
                    skipped += 1
                    continue
            except OSError:
                pass
            sftp.put(str(local), remote)
            uploaded += 1
        print(f"synced {uploaded} file(s), skipped {skipped} unchanged -> {dest_root}")

        if prune or dry_run:
            print(f"{'[dry-run] ' if dry_run else ''}pruning files that no longer exist locally:")
            removed = _prune(sftp, dest_root, local_rel, dry_run=dry_run)
            print(f"{'would remove' if dry_run else 'removed'} {removed} stale file(s)")

        sftp.close()
        return 0
    finally:
        c.close()


if __name__ == "__main__":
    raise SystemExit(main())
